AllCops:
  TargetRubyVersion: 2.6
  DisplayStyleGuide: true
  NewCops: enable

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false
