AllCops:
  TargetRubyVersion: 2.3
  DisplayStyleGuide: true

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Enabled: false
