AllCops:
  TargetRubyVersion: 3.0
  DisplayStyleGuide: true
  NewCops: enable

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Enabled: false
