sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.6
  - 2.3.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: ruby-head

before_install: gem install bundler -v 1.13.6

script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
